// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHaow822KVEKczQ8rXzCVXu1likojh7U',
    appId: '1:862175497641:web:9e6cf9b7d65a38cab808b8',
    messagingSenderId: '862175497641',
    projectId: 'first-pro-cheoo',
    authDomain: 'first-pro-cheoo.firebaseapp.com',
    storageBucket: 'first-pro-cheoo.firebasestorage.app',
    measurementId: 'G-44JR4JPXWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrSxYIdYBYe9uPLCPF8bxlaEg8mnL2Kk',
    appId: '1:862175497641:android:a976b0bbb493ca39b808b8',
    messagingSenderId: '862175497641',
    projectId: 'first-pro-cheoo',
    storageBucket: 'first-pro-cheoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnmoDSsBNYSDVb3D3AJRGcP6I9O9F860',
    appId: '1:862175497641:ios:292bee8fc0587fe8b808b8',
    messagingSenderId: '862175497641',
    projectId: 'first-pro-cheoo',
    storageBucket: 'first-pro-cheoo.firebasestorage.app',
    iosBundleId: 'com.example.pharrellPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVnmoDSsBNYSDVb3D3AJRGcP6I9O9F860',
    appId: '1:862175497641:ios:292bee8fc0587fe8b808b8',
    messagingSenderId: '862175497641',
    projectId: 'first-pro-cheoo',
    storageBucket: 'first-pro-cheoo.firebasestorage.app',
    iosBundleId: 'com.example.pharrellPhone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHaow822KVEKczQ8rXzCVXu1likojh7U',
    appId: '1:862175497641:web:074b713c64e29b5cb808b8',
    messagingSenderId: '862175497641',
    projectId: 'first-pro-cheoo',
    authDomain: 'first-pro-cheoo.firebaseapp.com',
    storageBucket: 'first-pro-cheoo.firebasestorage.app',
    measurementId: 'G-J0G0956G98',
  );
}
